apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: CloudNativeEntrepreneur
    provider: github
    repository: dev-cluster-monitoring
  name: cloudnativeentrepreneur-dev-cluster-monitoring
spec:
  description: Imported application for CloudNativeEntrepreneur/dev-cluster-monitoring
  httpCloneURL: https://github.com/CloudNativeEntrepreneur/dev-cluster-monitoring.git
  org: CloudNativeEntrepreneur
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: dev-cluster-monitoring
  scheduler:
    kind: ""
    name: ""
  url: git@github.com:CloudNativeEntrepreneur/dev-cluster-monitoring.git
