apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: CloudNativeEntrepreneur
    provider: github
    repository: auth
  name: cloudnativeentrepreneur-auth
spec:
  description: Imported application for CloudNativeEntrepreneur/auth
  httpCloneURL: https://github.com/CloudNativeEntrepreneur/auth.git
  org: CloudNativeEntrepreneur
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: auth
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/CloudNativeEntrepreneur/auth.git
