configAwsOrGcp:
  additional_secret_mount: psql-wale-creds
  additional_secret_mount_path: /var/secrets/google # or where ever you want to mount the file
  wal_gs_bucket: cldntventr-dev-psql-wale # name of bucket on where to save the WAL-E logs
  gcp_credentials: /var/secrets/google/key.json # combination of the mount path & key in the K8 resource. (i.e. key.json)
configKubernetes:
  enable_pod_antiaffinity: true
  pod_environment_configmap: jx/postgres-pod-config