dependencies:
- name: jxboot-resources
  repository: http://chartmuseum.jenkins-x.io
- alias: tekton
  name: tekton
  repository: http://chartmuseum.jenkins-x.io
- alias: prow
  condition: prow.enabled
  name: prow
  repository: http://chartmuseum.jenkins-x.io
- alias: lighthouse
  condition: lighthouse.enabled
  name: lighthouse
  repository: http://chartmuseum.jenkins-x.io
- alias: bucketrepo
  condition: bucketrepo.enabled
  name: bucketrepo
  repository: http://chartmuseum.jenkins-x.io
- name: jenkins-x-platform
  repository: http://chartmuseum.jenkins-x.io
- name: jx-app-replicator
  repository: http://chartmuseum.jenkins-x.io
  version: 1.0.16
- name: jx-app-ui
  repository: http://chartmuseum.jenkins-x.io
  version: 0.1.49
- name: keycloak-controller
  repository: https://kiwigrid.github.io
  version: 0.6.0
- name: prometheus-adapter
  version: 2.2.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: prometheus-operator
  version: 8.12.3
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: postgres-operator
  version: 1.5.0
  repository: https://raw.githubusercontent.com/zalando/postgres-operator/master/charts/postgres-operator/
- name: strimzi-kafka-operator
  version: 0.18.0
  repository: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/master/helm-charts/