{{- if .Values.certmanager.enabled }}
{{- if eq .Values.certmanager.production "true" }}
{{- if .Values.prodDomain }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: "tls-{{ "{{ .Values.prodDomain }}" | replace "." "-" }}-p"
  labels:
    jenkins.io/letsencrypt-service: production
spec:
  secretName: "tls-{{ "{{ .Values.prodDomain }}" | replace "." "-" }}-p"
  issuerRef:
    name: letsencrypt-prod
  commonName: "*.{{ "{{ .Values.prodDomain }}" }}"
  dnsNames:
  - "*.{{ "{{ .Values.prodDomain }}" }}"
{{- end }}
{{- end }}
{{- end }}
